on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  merge-develop-to-main:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fusionar develop en main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff origin/develop -m "Merge develop into main via GitHub Actions"
          git push origin main